language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change
# whitelist
branches:
  only:
    - master
env:
  global:
  - secure: P1sgq46dmYBOb/pvHGO2ACO/Zum5wbXebLJ6kLV+Ss97y0B+KWKGCrc9Hh9TG28mdzPMCHbJOFynfneet8irpEIL97PbSb2HFeKhiHJTeB4d0y60uaa6Y6Lmo+YCniubvw+FaeoXBYjImg2nDXslvKDTu6I0JKQ1pk8Fkqx45Sw=
  - secure: BTZcYkskQR5SleCK8enISTeSK/xR8rzvht/jEsYG5Ar7T/xa2USY2jaiIWzmd1t4hWkrSoubRCHuKt4oGi/fll75r9kPDLql9R1zaMmhEiKDsaEHZhuL6Ds8SVIgwdcpXN4IwiFfVOOxSTdpWcsNNbiQvCgtEIh0oqSk+jJArzI=
install:
- mvn -version -B
script:
- mvn -s .travis.maven.settings.xml verify -Dwildfly.logging.console.level=DEBUG -B -Pci
  | grep -vF "[INFO] Downloading:" | grep -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0
after_success:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
    mvn -s .travis.maven.settings.xml deploy -DskipTests ;
  fi
